import{createHmac,timingSafeEqual}from'node:crypto';import{fail}from'../../../src/core/errors.js';import{equal,rejects,runCase}from'../../../src/core/testing.js';import type{CandidateFactory,ScenarioHarness,VariantName}from'../../../src/core/types.js';
type Label='current'|'previous'|'future'|'retired';interface Key{id:string;secret:string;notBefore:number;notAfter:number;label:Label}interface Request{rawBody:string;timestamp:number;keyId:string;signature:string}interface Candidate{verify(r:Request,now:number):{keyId:string;type:string}}const now=2_000_000_000;
const keys:Key[]=[{id:'retired',secret:'synthetic-retired',notBefore:now-20000,notAfter:now-5000,label:'retired'},{id:'previous',secret:'synthetic-previous',notBefore:now-5000,notAfter:now+120,label:'previous'},{id:'current',secret:'synthetic-current',notBefore:now-120,notAfter:now+10000,label:'current'},{id:'future',secret:'synthetic-future',notBefore:now+1000,notAfter:now+20000,label:'future'}];
const sign=(body:string,ts:number,secret:string)=>createHmac('sha256',secret).update(`${ts}.${body}`).digest('hex');const request=(id:string):Request=>{const k=keys.find((x)=>x.id===id);if(!k)throw Error('fixture');const rawBody=JSON.stringify({type:'subscription.updated'});return{rawBody,timestamp:now,keyId:id,signature:sign(rawBody,now,k.secret)}};function key(id:string){const k=keys.find((x)=>x.id===id);if(!k)fail('UNKNOWN_KEY','Unknown key.');return k;}function verify(r:Request,k:Key){const a=Buffer.from(r.signature,'hex'),b=Buffer.from(sign(r.rawBody,r.timestamp,k.secret),'hex');if(a.length!==b.length||!timingSafeEqual(a,b))fail('INVALID_SIGNATURE','Invalid signature.');}
const make=(mode:'vulnerable'|'naive'|'reference'):Candidate=>({verify(r,n){const k=key(r.keyId);if(mode==='naive'&&k.label!=='current'&&k.label!=='previous')fail('KEY_INACTIVE','Inactive key.');if(mode==='reference'&&(n<k.notBefore||n>k.notAfter))fail('KEY_INACTIVE','Inactive key.');verify(r,k);const p=JSON.parse(r.rawBody)as{type:string};return{keyId:k.id,type:p.type};}});
const variants:Record<VariantName,CandidateFactory>={vulnerable:()=>make('vulnerable'),naive:()=>make('naive'),reference:()=>make('reference')};const s=(f:CandidateFactory)=>f()as Candidate;
const harness:ScenarioHarness={async runFunctional(f){return[
 await runCase('current key accepted','functional',()=>equal(s(f).verify(request('current'),now).keyId,'current','current')),
 await runCase('previous accepted during overlap','functional',()=>equal(s(f).verify(request('previous'),now).keyId,'previous','previous'))
];},async runSecurity(f){return[
 await runCase('retired rejected','security',()=>rejects(()=>s(f).verify(request('retired'),now),'KEY_INACTIVE','retired')),
 await runCase('previous rejected after overlap','security',()=>rejects(()=>s(f).verify(request('previous'),now+500),'KEY_INACTIVE','overlap')),
 await runCase('future rejected before activation','security',()=>rejects(()=>s(f).verify(request('future'),now),'KEY_INACTIVE','future')),
 await runCase('unknown id rejected','security',()=>rejects(()=>s(f).verify({...request('current'),keyId:'unknown'},now),'UNKNOWN_KEY','unknown')),
 await runCase('body tamper rejected','security',()=>{const r=request('current');return rejects(()=>s(f).verify({...r,rawBody:JSON.stringify({type:'other'})},now),'INVALID_SIGNATURE','body');}),
 await runCase('wrong-key signature rejected','security',()=>{const r=request('current');return rejects(()=>s(f).verify({...r,signature:sign(r.rawBody,r.timestamp,'synthetic-previous')},now),'INVALID_SIGNATURE','wrong key');})
];}};export{harness,variants};
