import{createHmac,timingSafeEqual}from'node:crypto';import{fail}from'../../../src/core/errors.js';import{equal,rejects,runCase}from'../../../src/core/testing.js';import type{CandidateFactory,ScenarioHarness,VariantName}from'../../../src/core/types.js';
interface Report{id:string;tenantId:string;name:string}interface Job{tenantId:string;reportId:string;mac?:string}interface Candidate{enqueue(tenantId:string,reportId:string):Job;execute(job:Job):string}
const reports:Report[]=[{id:'r-a',tenantId:'a',name:'Alpha Ledger'},{id:'r-b',tenantId:'b',name:'Beta Ledger'}];const secret='synthetic-queue-binding-secret';
const mac=(j:Pick<Job,'tenantId'|'reportId'>)=>createHmac('sha256',secret).update(`${j.tenantId}:${j.reportId}`).digest('hex');const same=(a:string,b:string)=>{const x=Buffer.from(a,'hex'),y=Buffer.from(b,'hex');return x.length===y.length&&timingSafeEqual(x,y);};
const make=(mode:'vulnerable'|'naive'|'reference'):Candidate=>({enqueue(tenant,reportId){const r=reports.find((x)=>x.id===reportId);if(mode!=='vulnerable'&&(!r||r.tenantId!==tenant))fail('FORBIDDEN','Report not authorized.');const job:Job={tenantId:tenant,reportId};if(mode==='reference')job.mac=mac(job);return job;},execute(job){if(mode==='reference'&&(!job.mac||!same(job.mac,mac(job))))fail('TAMPERED_JOB','Job binding is invalid.');const r=reports.find((x)=>x.id===job.reportId);if(!r||r.tenantId!==job.tenantId)fail('TENANT_MISMATCH','Job tenant does not own report.');return r.name;}});
const variants:Record<VariantName,CandidateFactory>={vulnerable:()=>make('vulnerable'),naive:()=>make('naive'),reference:()=>make('reference')};const s=(f:CandidateFactory)=>f()as Candidate;
const harness:ScenarioHarness={async runFunctional(f){return[await runCase('authorized job executes','functional',()=>{const c=s(f);equal(c.execute(c.enqueue('a','r-a')),'Alpha Ledger','report output');})];},async runSecurity(f){return[
 await runCase('cross-tenant enqueue denied','security',()=>rejects(()=>s(f).enqueue('a','r-b'),'FORBIDDEN','enqueue authorization')),
 await runCase('report id tamper rejected','security',()=>{const c=s(f),j=c.enqueue('a','r-a');return rejects(()=>c.execute({...j,reportId:'r-b'}),'TAMPERED_JOB','report binding');}),
 await runCase('tenant id tamper rejected','security',()=>{const c=s(f),j=c.enqueue('a','r-a');return rejects(()=>c.execute({...j,tenantId:'b'}),'TAMPERED_JOB','tenant binding');})
];}};export{harness,variants};
