import{createHash,createHmac,timingSafeEqual}from'node:crypto';import{fail}from'../../../src/core/errors.js';import{equal,rejects,runCase}from'../../../src/core/testing.js';import type{CandidateFactory,ScenarioHarness,VariantName}from'../../../src/core/types.js';
interface Request{rawBody:string;timestamp:number;eventId:string;contentDigest:string;signature:string}interface Event{type:string;amountCents:number;destinationAccount?:string;tenantId?:string}interface Candidate{verifyAndParse(r:Request):Event}const secret='synthetic-coverage-secret',ts=2_000_000_000;
const hash=(x:string)=>createHash('sha256').update(x).digest('hex');const sign=(r:Pick<Request,'timestamp'|'eventId'|'contentDigest'>)=>createHmac('sha256',secret).update(`${r.timestamp}.${r.eventId}.${r.contentDigest}`).digest('hex');const req=():Request=>{const rawBody=JSON.stringify({type:'payout.created',amountCents:5000});const b={timestamp:ts,eventId:'evt-1',contentDigest:hash(rawBody)};return{rawBody,...b,signature:sign(b)}};
function secure(a:string,b:string){const x=Buffer.from(a,'hex'),y=Buffer.from(b,'hex');return x.length===y.length&&timingSafeEqual(x,y)}function verifyHeader(r:Request){if(!secure(r.signature,sign(r)))fail('INVALID_SIGNATURE','Invalid header signature.')}function parse(raw:string):Event{const p=JSON.parse(raw)as Event;if(typeof p.type!=='string'||typeof p.amountCents!=='number')fail('INVALID_EVENT','Incomplete payload.');return p;}
const make=(mode:'vulnerable'|'naive'|'reference'):Candidate=>({verifyAndParse(r){verifyHeader(r);const p=parse(r.rawBody);if(mode==='naive'){const selected=JSON.stringify({type:p.type,amountCents:p.amountCents});if(hash(selected)!==r.contentDigest)fail('BODY_MISMATCH','Selected fields mismatch.');}if(mode==='reference'&&!secure(hash(r.rawBody),r.contentDigest))fail('BODY_MISMATCH','Raw body mismatch.');return p;}});
const variants:Record<VariantName,CandidateFactory>={vulnerable:()=>make('vulnerable'),naive:()=>make('naive'),reference:()=>make('reference')};const s=(f:CandidateFactory)=>f()as Candidate;const mutate=(r:Request,body:object)=>({...r,rawBody:JSON.stringify(body)});
const harness:ScenarioHarness={async runFunctional(f){return[await runCase('matching body accepted','functional',()=>equal(s(f).verifyAndParse(req()).amountCents,5000,'amount'))];},async runSecurity(f){return[
 await runCase('changed amount rejected','security',()=>rejects(()=>s(f).verifyAndParse(mutate(req(),{type:'payout.created',amountCents:999})),'BODY_MISMATCH','amount')),
 await runCase('unsigned destination rejected','security',()=>rejects(()=>s(f).verifyAndParse(mutate(req(),{type:'payout.created',amountCents:5000,destinationAccount:'attacker'})),'BODY_MISMATCH','destination')),
 await runCase('unsigned tenant route rejected','security',()=>rejects(()=>s(f).verifyAndParse(mutate(req(),{type:'payout.created',amountCents:5000,tenantId:'b'})),'BODY_MISMATCH','tenant route')),
 await runCase('digest metadata tamper rejected','security',()=>rejects(()=>s(f).verifyAndParse({...req(),contentDigest:'00'.repeat(32)}),'INVALID_SIGNATURE','digest header'))
];}};export{harness,variants};
