import { fail } from '../../../src/core/errors.js';import {deepEqual,rejects,runCase} from '../../../src/core/testing.js';import type{CandidateFactory,ScenarioHarness,VariantName}from'../../../src/core/types.js';
interface User{id:string;tenantId:string;role:'owner'|'admin'|'member';active:boolean}interface Candidate{disable(actorId:string,ids:string[]):User[];snapshot():User[]}
const seed:User[]=[{id:'owner-a',tenantId:'a',role:'owner',active:true},{id:'admin-a',tenantId:'a',role:'admin',active:true},{id:'m1',tenantId:'a',role:'member',active:true},{id:'m2',tenantId:'a',role:'member',active:true},{id:'m-b',tenantId:'b',role:'member',active:true}];
const make=(mode:'vulnerable'|'naive'|'reference'):Candidate=>{let users=seed.map((u)=>({...u}));return{snapshot:()=>users.map((u)=>({...u})),disable(actorId,ids){const actor=users.find((u)=>u.id===actorId);if(!actor||actor.role!=='admin')fail('FORBIDDEN','Admin required.');const targets=ids.map((id)=>users.find((u)=>u.id===id));if(targets.some((u)=>!u))fail('NOT_FOUND','User not found.');if(mode!=='vulnerable'&&targets.some((u)=>u?.tenantId!==actor.tenantId))fail('FORBIDDEN','Cross-tenant target.');if(mode==='reference'&&targets.some((u)=>u?.role==='owner'||u?.id===actor.id))fail('PROTECTED','Protected account.');if(mode==='vulnerable'){for(const id of ids){const u=users.find((x)=>x.id===id);if(u)u.active=false;}}else users=users.map((u)=>ids.includes(u.id)?{...u,active:false}:u);return users.filter((u)=>ids.includes(u.id)).map((u)=>({...u}));}}};
const variants:Record<VariantName,CandidateFactory>={vulnerable:()=>make('vulnerable'),naive:()=>make('naive'),reference:()=>make('reference')};const s=(f:CandidateFactory)=>f()as Candidate;
const harness:ScenarioHarness={async runFunctional(f){return[await runCase('ordinary users disabled atomically','functional',()=>{const c=s(f);c.disable('admin-a',['m1','m2']);deepEqual(c.snapshot().filter((u)=>['m1','m2'].includes(u.id)).map((u)=>u.active),[false,false],'disabled');})];},async runSecurity(f){return[
 await runCase('mixed tenant rejected without partial update','security',async()=>{const c=s(f);await rejects(()=>c.disable('admin-a',['m1','m-b']),'FORBIDDEN','mixed tenant');deepEqual(c.snapshot().filter((u)=>['m1','m-b'].includes(u.id)).map((u)=>u.active),[true,true],'atomic rollback');}),
 await runCase('owner protected','security',()=>rejects(()=>s(f).disable('admin-a',['owner-a']),'PROTECTED','owner')),
 await runCase('self disable protected','security',()=>rejects(()=>s(f).disable('admin-a',['admin-a']),'PROTECTED','self'))
];}};export{harness,variants};
