import{createHmac,timingSafeEqual}from'node:crypto';import{fail}from'../../../src/core/errors.js';import{equal,rejects,runCase}from'../../../src/core/testing.js';import type{CandidateFactory,ScenarioHarness,VariantName}from'../../../src/core/types.js';
interface Request{rawBody:string;timestamp:number;eventId?:string;signature:string}interface Candidate{handle(r:Request,now:number):{eventId:string;type:string}}const secret='synthetic-replay-secret',now=2_000_000_000;
const sign=(body:string,ts:number)=>createHmac('sha256',secret).update(`${ts}.${body}`).digest('hex');const valid=(id='evt-1',ts=now):Request=>{const rawBody=JSON.stringify({type:'invoice.paid',amount:12500});return{rawBody,timestamp:ts,eventId:id,signature:sign(rawBody,ts)}};
function verify(r:Request){const a=Buffer.from(r.signature,'hex'),b=Buffer.from(sign(r.rawBody,r.timestamp),'hex');if(a.length!==b.length||!timingSafeEqual(a,b))fail('INVALID_SIGNATURE','Invalid signature.');}function parse(r:Request){const p=JSON.parse(r.rawBody)as{type?:unknown};if(typeof p.type!=='string')fail('INVALID_EVENT','Missing type.');return p.type;}
const make=(mode:'vulnerable'|'naive'|'reference'):Candidate=>{const seen=new Set<string>();return{handle(r,n){verify(r);if(mode!=='vulnerable'&&Math.abs(n-r.timestamp)>300)fail('STALE','Stale delivery.');if(mode==='reference'){if(!r.eventId)fail('INVALID_EVENT','Missing event id.');if(seen.has(r.eventId))fail('REPLAY','Duplicate delivery.');seen.add(r.eventId);}return{eventId:r.eventId??'missing',type:parse(r)};}}};
const variants:Record<VariantName,CandidateFactory>={vulnerable:()=>make('vulnerable'),naive:()=>make('naive'),reference:()=>make('reference')};const s=(f:CandidateFactory)=>f()as Candidate;
const harness:ScenarioHarness={async runFunctional(f){return[await runCase('valid current webhook accepted','functional',()=>equal(s(f).handle(valid(),now).type,'invoice.paid','event type'))];},async runSecurity(f){return[
 await runCase('duplicate rejected','security',async()=>{const c=s(f),r=valid();c.handle(r,now);await rejects(()=>c.handle(r,now+1),'REPLAY','duplicate');}),
 await runCase('stale rejected','security',()=>rejects(()=>s(f).handle(valid('evt-stale',now-1000),now),'STALE','stale')),
 await runCase('tampered body rejected','security',()=>{const r=valid('evt-tamper');return rejects(()=>s(f).handle({...r,rawBody:JSON.stringify({type:'invoice.paid',amount:999})},now),'INVALID_SIGNATURE','tamper');}),
 await runCase('missing id rejected','security',()=>{const r=valid();delete r.eventId;return rejects(()=>s(f).handle(r,now),'INVALID_EVENT','missing id');})
];}};export{harness,variants};
