import{fail}from'../../../src/core/errors.js';import{deepEqual,invariant,rejects,runCase}from'../../../src/core/testing.js';import type{CandidateFactory,ScenarioHarness,VariantName}from'../../../src/core/types.js';
interface Candidate{list(tenantId:string,requested:string):string[]}const keys=['tenants/a/docs/one.pdf','tenants/a/docs/two.pdf','tenants/ab/docs/leak.pdf','tenants/b/docs/private.pdf','tenants/a-private/secret.txt'];
function safeSegments(value:string):boolean{return !value.includes('..')&&!value.includes('\\')&&!value.startsWith('/')&&!value.split('/').includes('');}
const make=(mode:'vulnerable'|'naive'|'reference'):Candidate=>({list(tenant,requested){let prefix:string;if(mode==='vulnerable')prefix=requested.startsWith('tenants/')?requested:`tenants/${tenant}/${requested.replace(/^\/+|\/+$/g,'')}/`;else if(mode==='naive'){prefix=requested.startsWith('tenants/')?requested:`tenants/${tenant}/${requested.replace(/^\/+|\/+$/g,'')}/`;if(!prefix.startsWith(`tenants/${tenant}`))fail('FORBIDDEN','Foreign prefix.');}else{if(requested.startsWith('tenants/'))fail('FORBIDDEN','Caller must not supply tenant root.');if(!safeSegments(requested))fail('INVALID_PREFIX','Unsafe prefix.');const root=`tenants/${tenant}/`;prefix=`${root}${requested.replace(/^\/+|\/+$/g,'')}/`;if(!prefix.startsWith(root))fail('FORBIDDEN','Outside tenant root.');}const result=keys.filter((k)=>k.startsWith(prefix));if(mode==='reference'&&result.some((k)=>!k.startsWith(`tenants/${tenant}/`)))fail('BOUNDARY','Returned key outside tenant.');return result;}});
const variants:Record<VariantName,CandidateFactory>={vulnerable:()=>make('vulnerable'),naive:()=>make('naive'),reference:()=>make('reference')};const s=(f:CandidateFactory)=>f()as Candidate;
const harness:ScenarioHarness={async runFunctional(f){return[await runCase('authorized directory listed','functional',()=>deepEqual(s(f).list('a','docs'),['tenants/a/docs/one.pdf','tenants/a/docs/two.pdf'],'own docs'))];},async runSecurity(f){return[
 await runCase('foreign prefix denied','security',()=>rejects(()=>s(f).list('a','tenants/b/docs'),'FORBIDDEN','foreign prefix')),
 await runCase('prefix collision denied','security',()=>rejects(()=>s(f).list('a','tenants/ab/docs'),'FORBIDDEN','collision')),
 await runCase('traversal-like prefix denied','security',()=>rejects(()=>s(f).list('a','../b/docs'),'INVALID_PREFIX','traversal')),
 await runCase('returned keys remain canonical','security',()=>{const result=s(f).list('a','docs');invariant(result.every((k)=>k.startsWith('tenants/a/')),'foreign key returned');})
];}};export{harness,variants};
